function(setup_vcpkg_before_project)
    if(DEFINED ENV{VCPKG_ROOT})
        set(vcpkg_toolchain_path "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
        get_filename_component(vcpkg_toolchain_path "${vcpkg_toolchain_path}" ABSOLUTE)
    endif()

    if(DEFINED CMAKE_TOOLCHAIN_FILE AND vcpkg_toolchain_path)
        get_filename_component(supplied_toolchain_file "${CMAKE_TOOLCHAIN_FILE}" ABSOLUTE)
        if(NOT supplied_toolchain_file STREQUAL vcpkg_toolchain_path)
            set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_TOOLCHAIN_FILE}" CACHE STRING "")
        endif()
    endif()

    if(vcpkg_toolchain_path AND EXISTS "${vcpkg_toolchain_path}")
        set(CMAKE_TOOLCHAIN_FILE "${vcpkg_toolchain_path}" CACHE STRING "" FORCE)
        message(STATUS "Using vcpkg from $ENV{VCPKG_ROOT}")
    endif()

    if(DEFINED ENV{VCPKG_DEFAULT_TRIPLET} AND NOT VCPKG_TARGET_TRIPLET)
        set(VCPKG_TARGET_TRIPLET "$ENV{VCPKG_DEFAULT_TRIPLET}" CACHE STRING "")
    endif()
    message(STATUS "Using vcpkg triplet ${VCPKG_TARGET_TRIPLET}")
endfunction()


function(diag_final_prop_dump)
    # Wrap up of settings printed on build
    message(STATUS "")
    message(STATUS "    == Final overview for ${PROJECT_NAME} ==" )
    message(STATUS "Version:              ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH} ${VERSION_TYPE} @ ${VERSION_HOST}")
    message(STATUS "Install prefix:       ${CMAKE_INSTALL_PREFIX}" )
    message(STATUS "Compiler:             ${CMAKE_CXX_COMPILER}" )
    message(STATUS "Compiler C:           ${CMAKE_C_COMPILER}" )
    message(STATUS "Using the following C++ compiler flags: ${CMAKE_CXX_FLAGS}")
    message(STATUS "CMake Module Path:    ${CMAKE_MODULE_PATH}" )
    message(STATUS "CMAKE_BUILD_TYPE:     ${CMAKE_BUILD_TYPE}" )
    message(STATUS "CMake binary dir:     ${CMAKE_BINARY_DIR}" )
    message(STATUS "System name:          ${CMAKE_SYSTEM_NAME}")
    message(STATUS "CMAKE_MODULE_PATH:    ${CMAKE_MODULE_PATH}")
    message(STATUS "CMAKE_PREFIX_PATH:    ${CMAKE_PREFIX_PATH}")
    message(STATUS "CMAKE_SOURCE_DIR:     ${CMAKE_SOURCE_DIR}")
    message(STATUS "EXTERNALS_DIR:        ${EXTERNALS_DIR}")
    message(STATUS "PROJECT_INCLUDE_DIR:  ${PROJECT_INCLUDE_DIR}")
    message(STATUS "COMPUTE_DIR:          ${COMPUTE_DIR}")
    message(STATUS "INSTALL_BIN_DIR:      ${INSTALL_BIN_DIR}")
    message(STATUS "" )
    message(STATUS "USE_EXPRTK:           ${USE_EXPRTK}")
    message(STATUS "FFMPEG_FOUND = ${FFMPEG_FOUND} ")
    message(STATUS "FFMPEG_INCLUDE_DIRS = ${FFMPEG_INCLUDE_DIRS} ")
    message(STATUS "FFMPEG_LIBRARIES = ${FFMPEG_LIBRARIES} ")
    message(STATUS "FFMPEG_DEFINITIONS = ${FFMPEG_DEFINITIONS} ")
    if(WIN32)
        message(STATUS "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}")
        message(STATUS "vcpkg_toolchain_path=${vcpkg_toolchain_path}")
        message(STATUS "VCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET}")
    endif()
 endfunction()